# ------------------------------------------------------------------------------------------------------------------------
# GHA Workflow triggered by "azd Up" command
# ------------------------------------------------------------------------------------------------------------------------
name: azd.cli.workflow
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
          - info
          - warning
          - debug 

permissions:
  id-token: write
  contents: write
  actions: read
  pages: write
  security-events: write
  checks: write
  issues: read
  pull-requests: read
  packages: read


jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: 'dev'
    # container:
    #   image: mcr.microsoft.com/azure-dev-cli-apps:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # Step 2: Install Azure Developer CLI (azd)
      - name: Install azd
        uses: Azure/setup-azd@v2

      - name: Azure Dev Provision
        run: azd provision --no-prompt
        env:
          AZURE_ENV_NAME: ${{ vars.AZD_NAME }}
          RESOURCEGROUP_LOCATION: ${{ vars.RESOURCEGROUP_LOCATION }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure Dev Deploy
        run: azd deploy --no-prompt
        env:
          AZURE_ENV_NAME: ${{ vars.AZD_NAME }}
          RESOURCEGROUP_LOCATION: ${{ vars.RESOURCEGROUP_LOCATION }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}